language: erlang
otp_release:
   - 17.1
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.2/Precompiled.zip
  - unzip -d elixir Precompiled.zip
  - wget https://github.com/alco/goon/releases/download/v1.1.1/goon_linux_amd64.tar.gz
  - mkdir -p goon && tar zxf goon_linux_amd64.tar.gz -C goon
before_script:
  - export PATH=`pwd`/elixir/bin:`pwd`/goon:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix deps.get
env:
  - PORT=4000 HTTP_HOST=http://example.com
script:
  - CONVERT_COMMAND=convert MIX_ENV=test mix test
