language: erlang
otp_release:
   - 17.1
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.1/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get
env:
  - PORT=4000 HTTP_HOST=http://example.com
script:
  - MIX_ENV=test mix test
